permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Zach Holman
url: http://helllth.github.io/left-fork/
description: A fantastic blog that is fantastic.
twitter: holman
